<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Create' => 'Создать',
    'Create From' => 'Создать источник',
    'Create To' => 'Создать потребителя',
    'Edit In ' => 'Изменить приход',
    'Edit Out ' => 'Изменить расход',
    'Are you sure you want to delete this item?' => '@@Точно удалить?@@',
    'Delete' => '@@Удалить@@',
    '+ I got cash again' => '+ Заработал еще',
    '+ Spend again' => '+ Еще потратила',
    'Category' => 'Категория',
    'For WHAT' => 'На ЧТО',
    'For what' => 'За что',
    'From' => 'Откуда',
    'Froms' => 'Источники',
    'How much' => 'Сколько',
    'In' => 'Приход',
    'Ins' => 'Приходы',
    'Logout ({username})' => 'Выход ({username})',
    'Out' => 'Расход',
    'Outs' => 'Расходы',
    'To' => 'Куда',
    'Tos' => 'Потребители',
    'Update' => 'Изменить',
    'Update {modelClass}: ' => 'Изменить {modelClass}: ',
    'When' => 'Когда',
    'Who' => 'Кто',
];
